version: 0.0

os: linux

files:
  -source: index.html
   destination: /var/www/html/

hooks:
BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStop:
    - location: stop-process.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: start-process.sh
      timeout: 180
      runas: root
